### ISSUE TITLE
An Error (e.g. invalid API Key) is not returned when using stream

### ISSUE THREAD

**Issue by bagindo** [Maxuss/chatgpt_rs#17]
Hi Maksim, thanks for a wonderful package.

I tried testing some unhappy path, e.g. inputting invalid API Key.

On the basic example, it returns the error saying invalid key.
But on the stream example, it doesn't return anything.

Probably this is due to the nature of stream function in Rust.

My understanding of Rust is still limited currently,
So I have no idea how to fix the issue myself.

Probably you can give some pointer on how to resolve this?

**Comment by Maxuss** [comment]
This issue happens because EventStream does not detect a valid stream body so it returns an empty stream. For example if you were to send a normal message with an invalid API key, it would return something like this:
```
BackendError { message: "Incorrect API key provided: sk-************************************************. You can find your API key at https://platform.openai.com/account/api-keys.", error_type: "invalid_request_error" }
```
Thank you for the report though! I am going to mention that streams can be empty in the docs for the next update.
