### ISSUE TITLE
Retention of questions and answers across the lifecycle

### ISSUE THREAD

**Issue by asami-okina** [Maxuss/chatgpt_rs#28]
## Question.
I'm very grateful for the library you provided.

We are currently trying to create a generic WebAPI server.
We envision an endpoint to receive API requests and would like to call `https://api.openai.com/v1/chat/completions` once per HTTP POST.

I checked [examples](https://github.com/Maxuss/chatgpt_rs/blob/master/examples/conversation.rs) on GitHub and found that it asks twice in one conversation and at the end of the lifecycle The result is that the conversation is terminated after the end of the lifecycle.
However, a typical WebAPI server would release the lifecycle after each request.
Therefore, the conversation is not continuing.

Could you please advise on how to ask a new question while continuing the previous question?

**Comment by Maxuss** [comment]
If I understand you correctly, you want to have a user send separate messages to a single conversation within multiple requests. In that case you could just save conversation state somewhere on server side, e.g. inside a database. Messages in conversation are stored as a simple `Vec`, so that shouldn't be a problem. You could then send conversation id to user, so they can later query specific conversation. Feel free to correct me if I got you wrong though,
